Fb = {"Burrow", "Adams", "Polamalu"}
S = {"Santos", "Ronaldo", "Messi"}
# print(f"Say hello to the football players {Fb}")
# print(f"Say hello to the soccer players {S}")
# print("We will be combing these teams using the Union method")
NewTeam = Fb.union(S)
# print(NewTeam)
# print("Let's show the difference between soccer from football players")
difS = S.difference(Fb)
# print(difS)
# print("Let's show the difference between football from soccer players")
difFb = Fb.difference(S)
# print(difFb)
empty = set()
# for i in range(1, 6):
#     x = input("Please input something: ")
#     empty.add(x)
# print(empty)
# x = input("Input a name to be deleted from the soccer team: ")
# S.remove(x)
# print(S)
S.clear()
Fb.clear()
NewTeam.clear()
empty.clear()
difS.clear()
difFb.clear()
print(S)
print(Fb)
print(empty)
print(NewTeam)
print(difS)
print(difFb)